apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    finalizers:
    - kubernetes.io/pv-protection
    name: test-cicd-mlbparks-app-pv 
  spec: 
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 10Gi
    nfs:
      path: /kvm/nfs/test-cicd/mlbparks/app/
      server: 55.55.55.1
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    finalizers:
    - kubernetes.io/pv-protection
    name: test-cicd-mlbparks-log-pv
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 10Gi
    nfs:
      path: /kvm/nfs/test-cicd/mlbparks/log/
      server: 55.55.55.1
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    namespace: test-cicd
    annotations:
    finalizers:
    - kubernetes.io/pvc-protection
    name: test-cicd-mlbparks-app-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    volumeName: test-cicd-mlbparks-app-pv
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    namespace: test-cicd
    annotations:
    finalizers:
    - kubernetes.io/pvc-protection
    name: test-cicd-mlbparks-log-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    volumeName: test-cicd-mlbparks-log-pv
kind: List
