apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    finalizers:
    - kubernetes.io/pv-protection
    name: test-cicd-postgresql-sonarqube-app-pv 
  spec: 
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 20Gi
    nfs:
      path: /kvm/nfs/test-cicd/postgresql-sonarqube/postgresql
      server: 55.55.55.1
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    namespace: test-cicd
    annotations:
    finalizers:
    - kubernetes.io/pvc-protection
    name: test-cicd-postgresql-sonarqube-app-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 20Gi
    volumeName: test-cicd-postgresql-sonarqube-app-pv
kind: List
