apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    finalizers:
    - kubernetes.io/pv-protection
    name: test-cicd-nexus-repository-manager-app-pv 
  spec: 
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 20Gi
    nfs:
      path: /kvm/nfs/test-cicd/nexus-repository-manager/nexus-data
      server: nfs.wsjeong.ocp4.local
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    namespace: test-cicd
    annotations:
    finalizers:
    - kubernetes.io/pvc-protection
    name: test-cicd-nexus-repository-manager-app-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 20Gi
    volumeName: test-cicd-nexus-repository-manager-app-pv
kind: List
